[project]
name = "ml-sandbox"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dagshub>=0.6.3",
    "ipykernel>=7.1.0",
    "mlflow>=3.7.0",
    "polars>=1.36.1",
    "scikit-learn>=1.8.0",
]
